server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/createryu/SpringCloudStudy.git
          searchPaths: config
          username: createryu
          password: yuqiliu666
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/